/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[Code]
      ,[Prefix]
      ,[EngName]
      ,[ArbName]
      ,[ArbName4S]
      ,[FormID]
      ,[IsRegistered]
      ,[FiscalYearDependant]
      ,[Rank]
      ,[Remarks]
      ,[ISAR]
      ,[ISAP]
      ,[IsGL]
      ,[ISFA]
      ,[IsINV]
      ,[IsHR]
      ,[ISMANF]
      ,[IsSYS]
      ,[RegUserID]
      ,[RegComputerID]
      ,[RegDate]
      ,[CancelDate]
      ,[ModifyUserID]
      ,[ModifyDate]
  FROM [Yama_VenusNet].[dbo].[sys_Modules]